# Generated by Django 2.2.7 on 2019-11-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_usario',
            fields=[
                ('id_usuario', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('primer_ap', models.CharField(max_length=20)),
                ('segundo_ap', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id_proyecto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('clase', models.CharField(max_length=15)),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('nombre_sin', models.CharField(max_length=30)),
                ('sintesis', models.TextField()),
                ('porsentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id_pdf', models.AutoField(primary_key=True, serialize=False)),
                ('pdf', models.FileField(default='', upload_to='archivos/%Y/%m/%d/')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notificacion', models.CharField(max_length=50)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('id_usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proyecto.datos_usario')),
            ],
        ),
        migrations.CreateModel(
            name='integrantes_proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encargo', models.CharField(max_length=10)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('id_usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proyecto.datos_usario')),
            ],
        ),
        migrations.AddField(
            model_name='datos_usario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.usuario'),
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('id_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.pdf')),
                ('id_usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proyecto.datos_usario')),
            ],
        ),
    ]
