# Generated by Django 2.2.7 on 2020-05-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='archivos/documentos/%Y/%m/%d/')),
                ('documento_nombre', models.CharField(max_length=50, null=True)),
                ('clase', models.CharField(max_length=40)),
                ('visible', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='lan_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='archivos/lan_page/%Y/%m/%d')),
                ('descripcion', models.TextField(default='')),
                ('link', models.TextField(default='')),
                ('visible', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='text_comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='fecha',
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdf_nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_usario',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='integrantes_proyecto',
            name='id_proyecto',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='integrantes_proyecto',
            name='id_usuario',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='notificacion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(default='', upload_to='archivos/archivos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='clase',
            field=models.CharField(max_length=40),
        ),
    ]
