# Generated by Django 2.2.7 on 2019-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_usario',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
