# Generated by Django 2.2.7 on 2019-12-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20191210_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='fecha',
        ),
    ]
