# Generated by Django 2.2.7 on 2019-12-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20191211_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='registros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notificacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdf_nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
