# Generated by Django 2.2.7 on 2019-12-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20191215_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registros',
            new_name='registro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='notificacion',
            new_name='registro',
        ),
    ]
