# Generated by Django 2.2.7 on 2019-12-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20191215_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='notificacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='registro',
            field=models.CharField(max_length=80),
        ),
    ]
