# Generated by Django 2.2.7 on 2019-12-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20191215_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='notificacion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registro',
            name='registro',
            field=models.CharField(max_length=150),
        ),
    ]
