# Generated by Django 2.2.7 on 2019-12-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20191215_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes_proyecto',
            name='id_usuario',
            field=models.CharField(max_length=5),
        ),
    ]
