# Generated by Django 2.2.7 on 2019-12-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_auto_20191217_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes_proyecto',
            name='id_proyecto',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='integrantes_proyecto',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.datos_usario'),
        ),
    ]
