# Generated by Django 2.2.7 on 2019-12-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20191217_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes_proyecto',
            name='id_usuario',
            field=models.CharField(max_length=5),
        ),
    ]
